all:
			@javac calc/CalculadoraServer.java
			@javac calc/CalculadoraServerImpl.java
			@javac calc/CalculadoraServerPublisher.java
			@javac calc/CalculadoraClient.java
server:
			@java calc.CalculadoraServerPublisher

client:
			@java calc.CalculadoraClient

clean:
			@rm -f calc/*.class calc/*~

